version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - MYSQL_DATABASE=devcode-todo
    ports:
      - 3306:3306
    volumes:
      - devcode-todo-mysql-data:/var/lib/mysql
      - devcode-todo-mysql-config:/etc/mysql
  golang-devcode-todo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DBNAME: devcode-todo
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_HOST: db
    volumes:
      - ./:/golang-devcode-todo
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  devcode-todo-mysql-data:
  devcode-todo-mysql-config: